version: "3.8"
services:
  chat-server:
    build: .
    environment:
      - DB_URL=postgresql://root:Stormchadow123@13.59.229.215:5432/pgdm
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - .:/app
