version: "3.8"

services:
pgdm-socket-messages:
    image: pgdm-socket-messages
    env_file: 
      - build/docker/env.env
    build:
      context: .
      dockerfile: build/docker/Dockerfile  
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - .:/app


